### ISSUE TITLE
URL Routing not working

### ISSUE THREAD

**Issue by angelo-v** [sm-react/storybook-chapters#3]
**Actual behaviour:**
Given I opened a story
When I refresh the page
*Then I am at the root of the storybook*

**Expected behaviour:**
Given I opened a story
When I refresh the page
*Then the story is still open*

**Comment by UsulPro** [comment]
@angelo-v Thank you for the issue.

This feature is really needed. And it's near to be done, so I hope It'll be implemented in the next release.
Actually it's in our [roadmap](https://github.com/sm-react/storybook-chapters#roadmap)

I hope after that this issue https://github.com/hadfieldn/storybook-filepath-chapters/issues/1 will be solved automatically as well

**Comment by angelo-v** [comment]
Thank you @UsulPro. Great to hear that!

**Comment by UsulPro** [comment]
This feature is added!
https://github.com/sm-react/storybook-chapters/releases/tag/0.4.0

Be happy if somebody check it out as well! :)
