### ISSUE TITLE
Migrate to @storybook/addon-chapters

### ISSUE THREAD

**Issue by UsulPro** [sm-react/storybook-chapters#4]
since v0.5.0 it's `@storybook/addon-chapters` on npm

сс @hadfieldn

**Comment by ndelangen** [comment]
Do you want to synchronise versioning with the other packages?

**Comment by UsulPro** [comment]
@ndelangen sure I want!
I think while it's under development it's more convenient to make minor releases with new features
When it be ready (soon) for major release I can stick it with storybook ver.
I'd like to transfer it under @storybooks org as well after that, what do you think?

**Comment by ndelangen** [comment]
Yeah migrating it to the organisation sounds good to me!
