### ISSUE TITLE
Can't resolve '@storybook/addon-chapters/register'

### ISSUE THREAD

**Issue by xareelee** [sm-react/storybook-chapters#6]
After following the guideline in the README file, I added a line to `addons.js`:

```js
import '@storybook/addon-chapters/register';
```

but when I ran storybook, it shows:

```
ERROR in ./storybook/addons.js
Module not found: Error: Can't resolve '@storybook/addon-chapters/register' in '{path_to_project}/storybook'
 @ ./storybook/addons.js 1:0-45
 @ multi ./storybook/addons.js ./~/@storybook/react-native/dist/manager/index.js
```

I check this repo and I find the `register.js` file in the `./dist/register.js` not `./register.js`.

**Comment by UsulPro** [comment]
@xareelee thanks for reporting this. 
It's fixed in `@storybook/addon-chapters@6.2` release
