### ISSUE TITLE
Can this lib support @storybook/react-native?

### ISSUE THREAD

**Issue by xareelee** [sm-react/storybook-chapters#7]
I use @storybook/react-native for a React Native project, and I did not install @storybook/react.

After install and run **storybook-chapters**, it shows:

```
error: bundling: UnableToResolveError: Unable to resolve module `@storybook/react` from `{path_to_project}/node_modules/@storybook/addon-chapters/dist/index.js`: 
Module does not exist in the module map or in these directories:
  {path_to_project}/node_modules/@storybook/addon-chapters/node_modules/@storybook
,  {path_to_project}/node_modules/@storybook

```

Do I need to install **@storybook/react**? Does it support React Native app development?

**Comment by xareelee** [comment]
I tried to add `@storybook/react` and it shows an error `document is not defined` when running a React Native app on my iPhone with storybook:

<img src=https://user-images.githubusercontent.com/804308/27759451-df5d99ce-5e63-11e7-8e40-ce599a823f5c.png width=240>

**Comment by orta** [comment]
There's a lot of work going in to nested hierarchies for the next release which should probably deprecate this

**Comment by UsulPro** [comment]
Sure we will discuss what to do with `storybook-chapters` after release

@xareelee I guess this addon does not support RN directly. 

You can wait for Storybook v3.2 release. Or ... any ideas about `storybook-chapters` are very welcome)

**Comment by xareelee** [comment]
Awesome, can't wait for it!

**Comment by FredyC** [comment]
@UsulPro Oh wow, I haven't even noticed that feature, that's definitely very cool, thank you!
