### ISSUE TITLE
Error when add 'import '@storybook/addon-chapters' in config

### ISSUE THREAD

**Issue by conradoramalho** [sm-react/storybook-chapters#8]
I have an error when I add the line 'import '@storybook/addon-chapters' in my config.

**Uncaught Error: Accessing nonexistent addons channel, see https://storybook.js.org/basics/faq/#why-is-there-no-addons-channel
    at AddonStore.getChannel (index.js:39)
    at setupChannel (store.js:297)**

Is this a bug or am I setting something wrong?

**Comment by UsulPro** [comment]
Hi @conradoramalho 

Yes, this is the known issue of storybook addons. I've already released a patch to fix it ([0.6.3](https://github.com/sm-react/storybook-chapters/releases/tag/0.6.3))

Please, feel free to reopen this issue if still have any questions!
