### ISSUE TITLE
Uncaught TypeError: (0 , _addonLinks.register) is not a function

### ISSUE THREAD

**Issue by ctumolosus** [sm-react/storybook-chapters#9]
Running into type error when `@storybook/addon-chapters@0.6.3` tries to register `@storybook/addon-links@3.4.1` here: https://github.com/sm-react/storybook-chapters/blob/master/register_es6.js#L11

**Comment by ac-coding** [comment]
I can't get it running for this exactly error either.
Any solution available?

**Comment by ctumolosus** [comment]
FWIW I settled with the native nesting story support (https://storybook.js.org/basics/writing-stories/#nesting-stories).

**Comment by mhauens** [comment]
Had the same error with "@storybook/react": "^4.0.0-rc.2",

**Comment by UsulPro** [comment]
I guess @storybook/addon-links should be moved to peerDependencies
Do you want to add PR for that?

**Comment by jaakkomutikainen** [comment]
Same issue for me, maybe I'll move on to using the native nesting support

**Comment by UsulPro** [comment]
This package is no longer maintained. I only apply vulnerabilities updates
